version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-container
    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity

    network_mode: service:pg-db
    
  pg-db:
    image: postgres:14.3
    restart: unless-stopped
    container_name: 'pg-db-container'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: campus
    ports:
      - "5433:5432"

volumes:
  postgres-data: